### PR TITLE
Fixes #19

### LINKED ISSUE #19: Incoming request setUrl($url) method
Hi @weierophinney , 

There is a bug over the setUrl which should set the object, but instead is setting back the same url. That makes the `getUrl()` returned being a string.

```php
    private function setUrl($url)
    {
        if (empty($url)) {
            throw new InvalidArgumentException('No URL provided to incoming request!');
        }

        $uri = new Uri($url);
        if (! $uri->isValid()) {
            throw new InvalidArgumentException('Invalid URL provided to incoming request!');
        }

        $this->url = $url;
    }
```

I am not sending a PR for I am not sure whether you accept as there is some changes to make it immutable etc.

Thank you.

### PR DESCRIPTION
**Pull request by harikt**
Hi @weierophinney , 

It may be good to merge this first and tag a version. 

Then merge the PR https://github.com/phly/http/pull/18 .

Thank you.

### CODE REVIEW

**Comment by weierophinney** [comment]
Any chance of a unit test to make sure it stays fixed? :-)

**Comment by harikt** [comment]
aah is it breaking ?

**Comment by harikt** [comment]
aah ok. I will add one :) .

**Comment by harikt** [comment]
Fixed :) .

**Comment by harikt** [comment]
On a side note, I did some experiments over https://github.com/harikt/ConduitExperiments . It took only a few hours to make some thing which works.

If you are willing, do you like to have a router middleware here ? Or do you have any other plans ?

**Comment by weierophinney** [comment]
Thanks!

**Comment by harikt** [comment]
@weierophinney did you forget to merge or is looking for something ?

**Comment by weierophinney** [comment]
I've been away from my computer and not had a chance to merge yet. (Been following the pr from my tablet.)

**Comment by harikt** [comment]
oh you don't use github merge :) .

**Comment by weierophinney** [comment]
Nope. On this repo, in particular, I tend to update the changelog on each merge, and, in this case, will be doing an immediate patch release after the merge.

**Pull request merged**
